[package]
name = "chakracore"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
chakracore-sys = { path = "../chakracore-sys" }
cxx = "1.0.199"
serde_json = "1.0.151"
thiserror = "2.0.20"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.26.1"

[features]
compile-cpp = ["chakracore-sys/compile-cpp"]
optimized-tests = ["chakracore-sys/optimized-tests"]
