[package]
name = "chakracore"
version = "0.1.0"
edition = "2021"

[dependencies]

[build-dependencies]
cc = { version = "1.1.24", features = ["parallel"] }
cmake = "0.1.51"

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 3
