[package]
name = "chakracore"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
cc = { version = "1.2.36", features = ["parallel"] }
cmake = "0.1.54"

[dev-dependencies]
pretty_assertions = "1.4.1"
rstest = "0.26.1"

[features]
compile-cpp = []
optimized-tests = []
