name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  # allow concurrent jobs on master, but not on PRs
  group: ${{ github.workflow }}-${{ (github.ref == 'refs/heads/master' && github.sha) || github.ref }}
  cancel-in-progress: true

jobs:
  build-rust:
    name: rust / ${{ matrix.os }} / ${{ matrix.build-type }}
    runs-on: ${{ matrix.os-image }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
          - ubuntu
        build-type:
          - debug
          - test
        include:
          - os: macos
            os-image: macos-latest
            deps: brew install ninja --quiet
          - os: ubuntu
            os-image: ubuntu-latest
            deps: sudo apt-get install -y ninja-build clang-19 lld-19 libc++-19-dev libc++abi-19-dev
          - build-type: debug
            features: "--features compile-cpp"
          - build-type: test
            features: "--features compile-cpp,optimized-tests"
    env:
      CARGO_TERM_COLOR: always
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: ${{ matrix.deps }}
      - run: |
          sudo ln -sf /usr/bin/clang++-19 /usr/bin/clang++
          sudo ln -sf /usr/bin/clang-19 /usr/bin/clang
        if: ${{ runner.os == 'Linux' }}
      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - name: Build
        run: cargo build ${{ matrix.features }} --all-targets -vv
      # TODO: don't fail fast
      - name: Run tests
        run: cargo nextest run ${{ matrix.features }}
      # TODO: don't fail fast
      - name: Run slow tests
        run: cargo nextest run ${{ matrix.features }} -- --ignored
        env:
          CHAKRA_TEST_SLOW: true
  build-cpp:
    name: cpp / ${{ matrix.os }} / ${{ matrix.build-type }}
    runs-on: ${{ matrix.os-image }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos
          - ubuntu
        build-type:
          - debug
          - test
        include:
          - os: macos
            os-image: macos-latest
            os-prefix: macos
            deps: brew install ninja --quiet
          - os: ubuntu
            os-image: ubuntu-latest
            os-prefix: linux
            deps: sudo apt-get install -y ninja-build clang-19 lld-19 libc++-19-dev libc++abi-19-dev
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: ${{ matrix.deps }}
      - name: Use clang-19
        run: |
          sudo ln -sf /usr/bin/clang++-19 /usr/bin/clang++
          sudo ln -sf /usr/bin/clang-19 /usr/bin/clang
        if: ${{ runner.os == 'Linux' }}
      - run: cargo check
      - run: cmake --preset ${{ matrix.os-prefix}}-${{ matrix.build-type }} -DCMAKE_COMPILE_WARNING_AS_ERROR=ON
      - run: cmake --build build-${{ matrix.os-prefix}}-${{ matrix.build-type }}
