name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: cmake-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  BUILD_TYPE: Debug
  CC: clang
  CXX: clang++

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        os:
        - macos-latest
        - macos-13
        - ubuntu-latest
        include:
        - os: macos-latest
          deps: brew install ninja icu4c
          cmake-flags: -DDISABLE_JIT=1 -DICU_INCLUDE_PATH=/opt/homebrew/opt/icu4c/include
          run-tests: false
        - os: macos-13
          deps: brew install ninja icu4c
          cmake-flags: -DICU_INCLUDE_PATH=/usr/local/opt/icu4c/include -DSTATIC_LIBRARY=ON
          run-tests: true
        - os: ubuntu-latest
          deps: sudo apt-get install -y ninja-build
          cmake-flags: ''
          run-tests: true

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/chakracore-cxx/cmake-build" >> "$GITHUB_OUTPUT"

    - name: Install dependencies
      run: ${{ matrix.deps }}

    - name: Create build directory
      run: mkdir -p ${{ steps.strings.outputs.build-output-dir }}

    - name: Configure CMake
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ${{ matrix.cmake-flags }} -G Ninja ${{ github.workspace }}/chakracore-cxx

    - name: Build
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ninja

    - name: Test
      if: ${{ matrix.run-tests }}
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ninja check
