name: C++

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: cxx-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    defaults:
      run:
        working-directory: ${{ github.workspace }}/chakracore-cxx/cmake-build
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        include:
          - os: macos-latest
            deps: brew install ninja icu4c@74
            cmake-flags: -DICU_INCLUDE_PATH=/opt/homebrew/opt/icu4c@74/include -DDISABLE_JIT=ON
          - os: ubuntu-latest
            deps: sudo apt-get install -y ninja-build
            cmake-flags: ''
    env:
      CMAKE_CXX_COMPILER: clang++
      CMAKE_C_COMPILER: clang
    steps:
      - uses: actions/checkout@v4
      - name: Create build directory
        working-directory: ${{ github.workspace }}/chakracore-cxx
        run: mkdir -p cmake-build
      - name: Install dependencies
        run: ${{ matrix.deps }}
      - name: Install mold linker
        if: matrix.os == 'ubuntu-latest'
        uses: rui314/setup-mold@v1
      - name: Configure CMake (debug)
        run: cmake -DCMAKE_BUILD_TYPE=Debug ${{ matrix.cmake-flags }} -GNinja ..
      - name: Build (debug)
        run: ninja
      - name: Configure CMake (test)
        run: cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ${{ matrix.cmake-flags }} -GNinja ..
      - name: Build (test)
        run: ninja
      - name: Test
        run: ninja check
      - name: Slow Tests
        run: ninja slow-check

  build-msvc:
    runs-on: windows-latest
    timeout-minutes: 120
    defaults:
      run:
        working-directory: ${{ github.workspace }}/chakracore-cxx
    steps:
      - uses: actions/checkout@v4
      - name: Build (debug)
        run: test\ci.buildone.cmd x64 debug
      - name: Build (test)
        run: test\ci.buildone.cmd x64 test
      - name: Test
        run: test\ci.testone.cmd x64 test
      - name: Slow Tests
        run: test\ci.testone.cmd x64 test --only-slow
