name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: rust-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        features:
          - '--no-default-features'
          - '--features optimized-test'
        include:
          - os: macos-latest
            deps: brew install ninja icu4c@74
          - os: ubuntu-latest
            deps: sudo apt-get install -y ninja-build
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        if: matrix.os != 'windows-latest'
        run: ${{ matrix.deps }}
      - name: Install cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Add msbuild to PATH
        if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: Set timezone
        if: matrix.os == 'windows-latest'
        run: tzutil /s "Pacific Standard time"
      - name: Build
        run: cargo build -vv ${{ matrix.features }}
      - name: Run tests
        run: cargo nextest run --no-fail-fast ${{ matrix.features }}
      - name: Run slow tests
        run: cargo nextest run --no-fail-fast --run-ignored only ${{ matrix.features }}
